# Default config
spring:
  jackson.default-property-inclusion: non_null
  jpa:
    hibernate.ddl-auto: validate
    properties:
      hibernate:
        query.mutation_strategy: org.hibernate.query.sqm.mutation.internal.inline.InlineMutationStrategy
        query.mutation_strategy.persistent:
          create_tables: false
          drop_tables: false
        query.mutation_strategy.global_temporary:
          create_tables: false
          drop_tables: false
  threads.virtual.enabled: true

springdoc.default-produces-media-type: application/json

management:
  endpoints.web:
    base-path: /
    exposure.include: [ "health", "info" ]
  endpoint.health.show-details: always

info.productId: HMPPS518

---
# Shared dev/test config
spring.config.activate.on-profile: dev
server.shutdown: immediate

spring:
  datasource.url: jdbc:tc:oracle:slim-faststart:///XEPDB1?TC_TMPFS=/testtmpfs:rw
  jpa.database: oracle
  jpa.hibernate.ddl-auto: create
  security.oauth2.resourceserver.jwt.jwk-set-uri: http://dummy/auth/.well-known/jwks.json
  cloud.aws.region.static: eu-west-2

logging.level:
  uk.gov.justice.digital.hmpps: DEBUG
