generic-service:
  ingress:
    host: supervision-packages-api.hmpps.service.justice.gov.uk

  env:
    SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWK_SET_URI: "https://sign-in.hmpps.service.justice.gov.uk/auth/.well-known/jwks.json"
    SENTRY_ENVIRONMENT: prod
